-- ============================================================================
-- PITWALL: Complete Supabase Database Schema
-- Run this SQL in your Supabase project:
-- Dashboard -> SQL Editor -> New query -> Paste and click "Run"
-- ============================================================================

-- Enable essential PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ----------------------------------------------------------------------------
-- 1. USERS & PREFERENCES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    provider TEXT NOT NULL DEFAULT 'password',
    role TEXT NOT NULL DEFAULT 'user',
    avatar TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.preferences (
    user_id BIGINT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    data JSONB NOT NULL DEFAULT '{
        "fav_drivers": [],
        "fav_constructors": [],
        "followed_sessions": ["race", "qualifying", "sprint"],
        "followed_events": [],
        "onboarded": false
    }'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_users_email_lower ON public.users (LOWER(email));

-- ----------------------------------------------------------------------------
-- 2. F1 REFERENCE / DIMENSION TABLES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.race_statuses (
    status_id INT PRIMARY KEY,
    status_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.seasons (
    year INT PRIMARY KEY,
    url TEXT
);

CREATE TABLE IF NOT EXISTS public.circuits (
    circuit_id INT PRIMARY KEY,
    circuit_ref VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    country VARCHAR(100),
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    alt INT,
    url TEXT
);

CREATE TABLE IF NOT EXISTS public.constructors (
    constructor_id INT PRIMARY KEY,
    constructor_ref VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    nationality VARCHAR(100),
    url TEXT
);

CREATE TABLE IF NOT EXISTS public.drivers (
    driver_id INT PRIMARY KEY,
    driver_ref VARCHAR(100) NOT NULL UNIQUE,
    driver_number INT,
    code VARCHAR(10),
    forename VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    dob DATE,
    nationality VARCHAR(100),
    url TEXT
);

-- ----------------------------------------------------------------------------
-- 3. CALENDAR & EVENT SESSIONS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.races (
    race_id INT PRIMARY KEY,
    year INT NOT NULL REFERENCES public.seasons(year),
    round INT NOT NULL,
    circuit_id INT NOT NULL REFERENCES public.circuits(circuit_id),
    name VARCHAR(255) NOT NULL,
    race_date DATE NOT NULL,
    race_time VARCHAR(50),
    url TEXT,
    fp1_date DATE,
    fp1_time VARCHAR(50),
    fp2_date DATE,
    fp2_time VARCHAR(50),
    fp3_date DATE,
    fp3_time VARCHAR(50),
    quali_date DATE,
    quali_time VARCHAR(50),
    sprint_date DATE,
    sprint_time VARCHAR(50),
    CONSTRAINT uq_race_year_round UNIQUE (year, round)
);

-- ----------------------------------------------------------------------------
-- 4. FACT TABLES (Race Results & Sessions)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.race_results (
    result_id INT PRIMARY KEY,
    race_id INT NOT NULL REFERENCES public.races(race_id) ON DELETE CASCADE,
    driver_id INT NOT NULL REFERENCES public.drivers(driver_id),
    constructor_id INT NOT NULL REFERENCES public.constructors(constructor_id),
    driver_number INT,
    grid INT NOT NULL,
    position INT,
    position_text VARCHAR(10),
    position_order INT NOT NULL,
    points NUMERIC(6, 2) NOT NULL DEFAULT 0.00,
    laps INT NOT NULL DEFAULT 0,
    race_time VARCHAR(50),
    milliseconds INT,
    fastest_lap INT,
    fastest_lap_rank INT,
    fastest_lap_time VARCHAR(50),
    fastest_lap_speed NUMERIC(6, 3),
    status_id INT NOT NULL REFERENCES public.race_statuses(status_id)
);

ALTER TABLE IF EXISTS public.race_results DROP CONSTRAINT IF EXISTS uq_result_race_driver;
CREATE INDEX IF NOT EXISTS idx_race_results_race_driver ON public.race_results(race_id, driver_id);

CREATE TABLE IF NOT EXISTS public.qualifying_results (
    qualify_id INT PRIMARY KEY,
    race_id INT NOT NULL REFERENCES public.races(race_id) ON DELETE CASCADE,
    driver_id INT NOT NULL REFERENCES public.drivers(driver_id),
    constructor_id INT NOT NULL REFERENCES public.constructors(constructor_id),
    driver_number INT,
    position INT NOT NULL,
    q1 VARCHAR(50),
    q2 VARCHAR(50),
    q3 VARCHAR(50),
    CONSTRAINT uq_qualifying_race_driver UNIQUE (race_id, driver_id)
);

CREATE TABLE IF NOT EXISTS public.sprint_results (
    sprint_result_id INT PRIMARY KEY,
    race_id INT NOT NULL REFERENCES public.races(race_id) ON DELETE CASCADE,
    driver_id INT NOT NULL REFERENCES public.drivers(driver_id),
    constructor_id INT NOT NULL REFERENCES public.constructors(constructor_id),
    driver_number INT,
    grid INT NOT NULL,
    position INT,
    position_text VARCHAR(10),
    position_order INT NOT NULL,
    points NUMERIC(6, 2) NOT NULL DEFAULT 0.00,
    laps INT NOT NULL DEFAULT 0,
    race_time VARCHAR(50),
    milliseconds INT,
    fastest_lap INT,
    fastest_lap_time VARCHAR(50),
    status_id INT NOT NULL REFERENCES public.race_statuses(status_id),
    CONSTRAINT uq_sprint_race_driver UNIQUE (race_id, driver_id)
);

CREATE TABLE IF NOT EXISTS public.pit_stops (
    race_id INT NOT NULL REFERENCES public.races(race_id) ON DELETE CASCADE,
    driver_id INT NOT NULL REFERENCES public.drivers(driver_id),
    stop_number INT NOT NULL,
    lap INT NOT NULL,
    stop_time VARCHAR(50),
    stop_duration VARCHAR(50),
    milliseconds INT,
    PRIMARY KEY (race_id, driver_id, stop_number)
);

CREATE TABLE IF NOT EXISTS public.lap_times (
    race_id INT NOT NULL REFERENCES public.races(race_id) ON DELETE CASCADE,
    driver_id INT NOT NULL REFERENCES public.drivers(driver_id),
    lap INT NOT NULL,
    position INT NOT NULL,
    lap_time_str VARCHAR(50),
    milliseconds INT NOT NULL,
    PRIMARY KEY (race_id, driver_id, lap)
);

CREATE TABLE IF NOT EXISTS public.driver_standings (
    driver_standings_id INT PRIMARY KEY,
    race_id INT NOT NULL REFERENCES public.races(race_id) ON DELETE CASCADE,
    driver_id INT NOT NULL REFERENCES public.drivers(driver_id),
    points NUMERIC(6, 2) NOT NULL DEFAULT 0.00,
    position INT NOT NULL,
    position_text VARCHAR(10),
    wins INT NOT NULL DEFAULT 0,
    CONSTRAINT uq_driver_standings_race_driver UNIQUE (race_id, driver_id)
);

CREATE TABLE IF NOT EXISTS public.constructor_standings (
    constructor_standings_id INT PRIMARY KEY,
    race_id INT NOT NULL REFERENCES public.races(race_id) ON DELETE CASCADE,
    constructor_id INT NOT NULL REFERENCES public.constructors(constructor_id),
    points NUMERIC(6, 2) NOT NULL DEFAULT 0.00,
    position INT NOT NULL,
    position_text VARCHAR(10),
    wins INT NOT NULL DEFAULT 0,
    CONSTRAINT uq_constructor_standings_race_cons UNIQUE (race_id, constructor_id)
);

CREATE TABLE IF NOT EXISTS public.constructor_results (
    constructor_results_id INT PRIMARY KEY,
    race_id INT NOT NULL REFERENCES public.races(race_id) ON DELETE CASCADE,
    constructor_id INT NOT NULL REFERENCES public.constructors(constructor_id),
    points NUMERIC(6, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50)
);

-- ----------------------------------------------------------------------------
-- 5. PERFORMANCE INDEXES
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_race_results_race_id ON public.race_results(race_id);
CREATE INDEX IF NOT EXISTS idx_race_results_driver_id ON public.race_results(driver_id);
CREATE INDEX IF NOT EXISTS idx_race_results_constructor_id ON public.race_results(constructor_id);
CREATE INDEX IF NOT EXISTS idx_races_year_round ON public.races(year, round);
CREATE INDEX IF NOT EXISTS idx_lap_times_race_driver ON public.lap_times(race_id, driver_id);
CREATE INDEX IF NOT EXISTS idx_driver_standings_race ON public.driver_standings(race_id);
CREATE INDEX IF NOT EXISTS idx_cons_standings_race ON public.constructor_standings(race_id);

-- Trigram search indexes for fast autocomplete in search pickers
CREATE INDEX IF NOT EXISTS idx_drivers_name_trgm ON public.drivers USING gin ((forename || ' ' || surname) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_constructors_name_trgm ON public.constructors USING gin (name gin_trgm_ops);

-- ----------------------------------------------------------------------------
-- 6. MATERIALIZED VIEWS & ML DATASET VIEW
-- ----------------------------------------------------------------------------
CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_driver_summaries AS
SELECT 
    d.driver_id,
    d.driver_ref,
    d.code,
    d.driver_number,
    (d.forename || ' ' || d.surname) AS name,
    d.forename,
    d.surname,
    d.dob,
    d.nationality,
    d.url,
    COUNT(r.result_id) AS starts,
    COUNT(CASE WHEN r.position_order = 1 THEN 1 END) AS wins,
    COUNT(CASE WHEN r.position_order <= 3 THEN 1 END) AS podiums,
    COUNT(CASE WHEN r.grid = 1 THEN 1 END) AS poles,
    COALESCE(SUM(r.points), 0) AS points,
    COUNT(CASE WHEN r.position_order IS NULL OR r.position_order > 20 THEN 1 END) AS dnfs,
    COUNT(CASE WHEN r.fastest_lap_rank = 1 THEN 1 END) AS fastest_laps,
    MIN(r.position_order) AS best_finish,
    MIN(rc.year) AS first_season,
    MAX(rc.year) AS last_season,
    ROUND((COUNT(CASE WHEN r.position_order = 1 THEN 1 END)::NUMERIC / NULLIF(COUNT(r.result_id), 0)), 4) AS win_rate,
    ROUND((COUNT(CASE WHEN r.position_order <= 3 THEN 1 END)::NUMERIC / NULLIF(COUNT(r.result_id), 0)), 4) AS podium_rate
FROM public.drivers d
LEFT JOIN public.race_results r ON d.driver_id = r.driver_id
LEFT JOIN public.races rc ON r.race_id = rc.race_id
GROUP BY d.driver_id, d.driver_ref, d.code, d.driver_number, d.forename, d.surname, d.dob, d.nationality, d.url;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_driver_summaries_id ON public.mv_driver_summaries(driver_id);

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_constructor_summaries AS
SELECT 
    c.constructor_id,
    c.constructor_ref,
    c.name,
    c.nationality,
    c.url,
    COUNT(r.result_id) AS entries,
    COUNT(DISTINCT r.race_id) AS races,
    COUNT(CASE WHEN r.position_order = 1 THEN 1 END) AS wins,
    COUNT(CASE WHEN r.position_order <= 3 THEN 1 END) AS podiums,
    COUNT(CASE WHEN r.grid = 1 THEN 1 END) AS poles,
    COALESCE(SUM(r.points), 0) AS points,
    COUNT(DISTINCT r.driver_id) AS drivers_count,
    MIN(rc.year) AS first_season,
    MAX(rc.year) AS last_season,
    ROUND((COUNT(CASE WHEN r.position_order = 1 THEN 1 END)::NUMERIC / NULLIF(COUNT(DISTINCT r.race_id), 0)), 4) AS win_rate
FROM public.constructors c
LEFT JOIN public.race_results r ON c.constructor_id = r.constructor_id
LEFT JOIN public.races rc ON r.race_id = rc.race_id
GROUP BY c.constructor_id, c.constructor_ref, c.name, c.nationality, c.url;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_cons_summaries_id ON public.mv_constructor_summaries(constructor_id);

-- ML Dataset view (replaces static f1.csv)
CREATE OR REPLACE VIEW public.v_f1_ml_dataset AS
SELECT 
    r.result_id,
    r.race_id,
    r.driver_id,
    r.constructor_id,
    rc.circuit_id,
    rc.year AS season,
    rc.round,
    rc.name AS race_name,
    rc.race_date AS date,
    rc.race_time AS race_start_time,
    c.name AS circuit_name,
    c.location,
    c.country AS circuit_country,
    c.lat,
    c.lng,
    c.alt,
    c.circuit_ref,
    (d.forename || ' ' || d.surname) AS driver_name,
    d.driver_number,
    d.code,
    d.nationality AS nationality_driver,
    d.dob,
    d.driver_ref,
    cons.name AS constructor_name,
    cons.nationality AS nationality_constructor,
    cons.constructor_ref,
    r.grid,
    r.position,
    r.position_text,
    r.position_order,
    r.points,
    r.laps,
    r.milliseconds,
    r.fastest_lap,
    r.fastest_lap_rank AS rank,
    r.fastest_lap_time,
    r.fastest_lap_speed,
    r.status_id
FROM public.race_results r
JOIN public.races rc ON r.race_id = rc.race_id
JOIN public.circuits c ON rc.circuit_id = c.circuit_id
JOIN public.drivers d ON r.driver_id = d.driver_id
JOIN public.constructors cons ON r.constructor_id = cons.constructor_id;

-- ----------------------------------------------------------------------------
-- 7. ROW LEVEL SECURITY (RLS) POLICIES
-- ----------------------------------------------------------------------------
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.race_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.circuits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.constructors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.races ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.race_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qualifying_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sprint_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pit_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lap_times ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_standings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.constructor_standings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.constructor_results ENABLE ROW LEVEL SECURITY;

-- Backend and User policies
DROP POLICY IF EXISTS "Allow backend API access to users" ON public.users;
CREATE POLICY "Allow backend API access to users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow backend API access to preferences" ON public.preferences;
CREATE POLICY "Allow backend API access to preferences" ON public.preferences FOR ALL USING (true) WITH CHECK (true);

-- Allow public read access to all F1 data tables
DO $$ 
DECLARE
    tbl text;
BEGIN
    FOR tbl IN 
        SELECT tablename 
        FROM pg_tables 
        WHERE schemaname = 'public' 
          AND tablename NOT IN ('users', 'preferences')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Allow public read access" ON public.%I;', tbl);
        EXECUTE format('CREATE POLICY "Allow public read access" ON public.%I FOR SELECT USING (true);', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Allow service role write access" ON public.%I;', tbl);
        EXECUTE format('CREATE POLICY "Allow service role write access" ON public.%I FOR ALL USING (true) WITH CHECK (true);', tbl);
    END LOOP;
END $$;
