-- ============================================================================
-- PITWALL: Supabase Database Schema
-- Run this SQL in your Supabase project:
-- Dashboard -> SQL Editor -> New query -> Paste and click "Run"
-- ============================================================================

-- 1. Users table (Fan accounts and Analyst Admin)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    provider TEXT NOT NULL DEFAULT 'password',
    role TEXT NOT NULL DEFAULT 'user',
    avatar TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Preferences table (Fan favorite drivers, teams, followed sessions & events)
CREATE TABLE IF NOT EXISTS public.preferences (
    user_id BIGINT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    data JSONB NOT NULL DEFAULT '{
        "fav_drivers": [],
        "fav_constructors": [],
        "followed_sessions": ["race", "qualifying", "sprint"],
        "followed_events": [],
        "onboarded": false
    }'::jsonb
);

-- 3. Case-insensitive email lookup index
CREATE INDEX IF NOT EXISTS idx_users_email_lower ON public.users (LOWER(email));

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preferences ENABLE ROW LEVEL SECURITY;

-- 5. Policies allowing full API access for the PITWALL backend
-- (Works with both service_role key and anon key)
DROP POLICY IF EXISTS "Allow backend API access to users" ON public.users;
CREATE POLICY "Allow backend API access to users" ON public.users
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow backend API access to preferences" ON public.preferences;
CREATE POLICY "Allow backend API access to preferences" ON public.preferences
    FOR ALL USING (true) WITH CHECK (true);
